mapList:
  handler: src/handlers/maps/handler.list
  events:
    - http:
        path: /maps
        method: get
        cors: true

mapAdd:
  handler: src/handlers/maps/handler.add
  events:
    - http:
        path: /maps
        method: post
        cors: true
        authorizer: auth

mapDelete:
  handler: src/handlers/maps/handler.delete
  events:
    - http:
        path: /maps/{id}
        method: delete
        cors: true
        authorizer: auth
