usersList:
  handler: src/handlers/users/handler.list
  events:
    - http: get /users

userGet:
  handler: src/handlers/users/handler.get
  events:
    - http: get /users/{id}

userAdd:
  handler: src/handlers/users/handler.add
  events:
    - http:
        path: /users
        method: post
        authorizer: auth

userUpdate:
  handler: src/handlers/users/handler.update
  events:
    - http:
        path: /users/{id}
        method: put
        authorizer: auth

userDelete:
  handler: src/handlers/users/handler.delete
  events:
    - http:
        path: /users/{id}
        method: delete
        authorizer: auth

usersRank:
  handler: src/handlers/users/handler.rank
  events:
    - http: get /users-rank

userRank:
  handler: src/handlers/users/handler.getRank
  events:
    - http: get /users/{id}/rank

