usersList:
  handler: src/handlers/users/handler.list
  events:
    - http:
        path: /users
        method: get
        cors: true

userGet:
  handler: src/handlers/users/handler.get
  events:
    - http:
        path: /users/{id}
        method: get
        cors: true

userAdd:
  handler: src/handlers/users/handler.add
  events:
    - http:
        path: /users
        method: post
        cors: true
        authorizer: auth

userUpdate:
  handler: src/handlers/users/handler.update
  events:
    - http:
        path: /users/{id}
        method: put
        cors: true
        authorizer: auth

userDelete:
  handler: src/handlers/users/handler.delete
  events:
    - http:
        path: /users/{id}
        method: delete
        cors: true
        authorizer: auth

usersRank:
  handler: src/handlers/users/handler.rank
  events:
    - http:
        path: /users-rank
        method: get
        cors: true

userRank:
  handler: src/handlers/users/handler.getRank
  events:
    - http:
        path: /users/{id}/rank
        method: get
        cors: true

